FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/UCT /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

RUN apt-get install -y wget g++ unzip zip nano python cmake git libssl-dev libgmp-dev libtinfo5 libprotobuf-dev

RUN wget https://github.com/bazelbuild/bazel/releases/download/5.3.0/bazel-5.3.0-installer-linux-x86_64.sh && \
    chmod +x bazel-5.3.0-installer-linux-x86_64.sh && \
    ./bazel-5.3.0-installer-linux-x86_64.sh --user

ENV PATH=/root/bin:$PATH
